name: textspan_parser
description: >-
  A package to create TextSpans from a textual representation.
  The typical use case is to allow text styling to be determined 
  by the translator when localizing an app.

  Example:
  en-US: Unfortunately, my {\italic neighbor} had eaten my shoes.
  da: Desværre havde min {\italic nabo} spist mine sko.

  Notice how neighbor (= nabo) and had (= havde) are reversed in 
  danish (da), compared to american english (en-US). This implies 
  that if we want "neighbor" to appear in italic, we need to decide
  where the text should be split in spans during translation.

version: 0.0.1
homepage: https://github.com/nielsenko/textspan_parser

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  petitparser: any  
  golden_toolkit: any

dev_dependencies:
  flutter_test:
    sdk: flutter  
  google_fonts: any
  path_provider: any
  test: any

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
