name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and generate coverage
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

  multi-platform-test:
    name: ${{ matrix.os }}-${{ matrix.channel }}-${{ matrix.pub }}d
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta, master]
        pub: [downgrade, upgrade]
        
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Install ${{ matrix.pub }}d dependencies
        run: flutter pub ${{ matrix.pub }}

      - name: Run tests
        run: flutter test
